// Auto-generated calibration header
// Generated by MATLAB from Sensor3.xlsx

#ifndef CALIBRATION3_H
#define CALIBRATION3_H

// Linear calibration model:
// distance_mm = CAL3_A * time_us + CAL3_B

const float CAL3_A = 0.1751021472f;
const float CAL3_B = -1.8914020427f;

#endif // CALIBRATION3_H
