// Auto-generated calibration header
// Generated by MATLAB from Sensor2.xlsx

#ifndef CALIBRATION2_H
#define CALIBRATION2_H

// Linear calibration model:
// distance_mm = CAL2_A * time_us + CAL2_B

const float CAL2_A = 0.1749264464f;
const float CAL2_B = 10.7584005379f;

#endif // CALIBRATION2_H
