// Auto-generated calibration header
// Generated by MATLAB from Sensor5.xlsx

#ifndef CALIBRATION5_H
#define CALIBRATION5_H

// Linear calibration model:
// distance_mm = CAL5_A * time_us + CAL5_B

const float CAL5_A = 0.1754696852f;
const float CAL5_B = -0.1896181936f;

#endif // CALIBRATION5_H
